### ISSUE TITLE
Make identifier constraint optional

### ISSUE THREAD

**Issue by physikerwelt** [ER-FIZKarlsruhe/fiz-oai-backend#1]
https://github.com/ER-FIZKarlsruhe/fiz-oai-backend/blob/8c29982f5f852ad423bf201779c4be05b68bb570/src/main/java/de/fiz/oai/backend/controller/ItemController.java#L151-L152

The line above checks if the identifier is contained in the content. Is this constraint standard-conforming? The check especially does not parse the XML file, so the check would pass even if the identifier is a part of a comment. I suggest either replacing the hard constraint with a warning or making the check configurable so that it can be disabled via config.

**Comment by stefanbozic** [comment]
>Is this constraint standard-conforming?

There is not standard for oai repositories. But this check helps us to avoid bad data in the backend.

You can opt-out this check via the new configuration "checkItemIdentifierInContent" in fiz-oai-backend.properties

    boolean checkItemIdentifierInContent = Boolean.valueOf(config.getProperty("checkItemIdentifierInContent", "true"));
    
    if (checkItemIdentifierInContent && !content.contains(item.getIdentifier())) {
      throw new WebApplicationException("Cannot find the identifier in the content!", Status.BAD_REQUEST);
    }
